/**
 * GET /api/setup/script
 *
 * Returns the bulletproof PowerShell installer for the yeehee Signal Daemon.
 * Pattern matches clinix.id Mira worker - user pastes a single-line bootstrap
 * that downloads this script, runs it with named flags. No clipboard fragility.
 *
 * Defensive against every realistic failure on a fresh Windows PC:
 *  - PowerShell 5.1 native-cmd stderr quirk (Invoke-Native helper)
 *  - MS Store Python alias detection
 *  - Missing winget (clear error message + manual instructions)
 *  - Network retry for git / pip
 *  - Supabase reachability check pre-install (fail fast on bad creds)
 *  - Post-launch daemon liveness verify
 *  - ASCII-only body + UTF-8 BOM (PS 5.1 codepage compat)
 */
import { NextResponse } from 'next/server'

export const dynamic = 'force-dynamic'
export const runtime  = 'edge'

const REPO_URL    = 'https://github.com/proreyhanwijaya111/yeehee.git'
const DEFAULT_DIR = 'yeehee-daemon'
const DEFAULT_PORT = '3031'
const SERVICE_NAME = 'yeehee-signal-daemon'

const SCRIPT = `# yeehee Signal Daemon - bulletproof installer (auto-generated by yeehee.vercel.app)
# Worker terpisah dari Mira WA Worker (Clinix). Folder: $HOME\\${DEFAULT_DIR}, port ${DEFAULT_PORT}.

[CmdletBinding()]
param(
    [Parameter(Mandatory=$true)]  [string] $SupabaseUrl,
    [Parameter(Mandatory=$true)]  [string] $SupabaseAnonKey,
    [Parameter(Mandatory=$false)] [string] $UserId      = "default",
    [Parameter(Mandatory=$false)] [string] $Port        = "${DEFAULT_PORT}",
    [Parameter(Mandatory=$false)] [string] $InstallDir  = "$HOME\\${DEFAULT_DIR}",
    [Parameter(Mandatory=$false)] [string] $PipMirror   = "https://pypi.tuna.tsinghua.edu.cn/simple",  # default Tsinghua (cepat dari Asia/Indonesia)
    [Parameter(Mandatory=$false)] [switch] $InstallServiceOnly,
    [Parameter(Mandatory=$false)] [switch] $StopOnly
)

# Use 'Continue' to avoid PS 5.1 native-cmd stderr quirk. We check exit codes manually.
$ErrorActionPreference = 'Continue'
$VerbosePreference     = 'SilentlyContinue'
$ProgressPreference    = 'SilentlyContinue'

# ============================================================================
# Helpers
# ============================================================================

function Write-Step ($Msg, $Color = 'Cyan') {
    Write-Host ""
    Write-Host "[yeehee] $Msg" -ForegroundColor $Color
}

function Write-OK ($Msg) {
    Write-Host "  [OK] $Msg" -ForegroundColor Green
}

function Write-Warn ($Msg) {
    Write-Host "  [WARN] $Msg" -ForegroundColor Yellow
}

function Refresh-Path {
    $env:PATH = [Environment]::GetEnvironmentVariable("PATH", "Machine") + ";" +
                [Environment]::GetEnvironmentVariable("PATH", "User")
}

# Native-cmd wrapper: captures exit code without falling for PS 5.1 stderr quirk.
function Invoke-Native {
    param(
        [Parameter(Mandatory)] [string]   $Cmd,
        [Parameter(Mandatory)] [string[]] $Args,
        [string] $Label = $Cmd,
        [switch] $Quiet,
        [int]    $Retries = 0
    )
    $attempt = 0
    while ($true) {
        $attempt++
        if ($Quiet) {
            & $Cmd @Args *>$null
        } else {
            & $Cmd @Args 2>&1 | ForEach-Object { Write-Host "    $_" -ForegroundColor DarkGray }
        }
        $code = $LASTEXITCODE
        if ($code -eq 0) { return }
        if ($attempt -gt $Retries) {
            throw "$Label failed (exit code $code)"
        }
        Write-Warn "$Label exit $code, retry $attempt/$Retries dalam 3 detik..."
        Start-Sleep -Seconds 3
    }
}

# Detect MS Store Python alias (Win11 ships a stub python.exe that opens Store).
function Test-RealPython {
    $py = Get-Command python -ErrorAction SilentlyContinue
    if (-not $py) { return $false }
    # MS Store stub lives under WindowsApps and reports 0-byte length when queried via Get-Item
    if ($py.Source -like "*WindowsApps*") {
        try {
            $size = (Get-Item $py.Source -ErrorAction Stop).Length
            if ($size -lt 100KB) { return $false }
        } catch {
            return $false
        }
    }
    # Try to actually run it
    try {
        $ver = & python --version 2>&1
        if ($LASTEXITCODE -ne 0) { return $false }
        return ($ver -match 'Python 3\\.(1[0-9]|[2-9][0-9])')   # 3.10+
    } catch {
        return $false
    }
}

function Test-Winget {
    return [bool](Get-Command winget -ErrorAction SilentlyContinue)
}

function Install-Tool {
    param([string]$WingetId, [string]$Label)
    if (-not (Test-Winget)) {
        throw "winget tidak tersedia. Update Windows ke 10 1809+ / 11, atau install $Label manual dulu."
    }
    Write-Host "  installing $Label via winget..." -ForegroundColor Yellow
    & winget install --id $WingetId -e --accept-source-agreements --accept-package-agreements --silent --disable-interactivity 2>&1 |
        ForEach-Object { Write-Host "    $_" -ForegroundColor DarkGray }
    Refresh-Path
}

# Add common Python install dirs to PATH (winget user-scope sometimes does not propagate)
function Add-PythonToPath {
    $candidates = @(
        "$env:LOCALAPPDATA\\Programs\\Python\\Python313",
        "$env:LOCALAPPDATA\\Programs\\Python\\Python313\\Scripts",
        "$env:LOCALAPPDATA\\Programs\\Python\\Python312",
        "$env:LOCALAPPDATA\\Programs\\Python\\Python312\\Scripts",
        "C:\\Python313", "C:\\Python313\\Scripts",
        "C:\\Python312", "C:\\Python312\\Scripts"
    )
    foreach ($dir in $candidates) {
        if ((Test-Path $dir) -and ($env:PATH -notlike "*$dir*")) {
            $env:PATH = "$dir;$env:PATH"
        }
    }
}

# ============================================================================
# Stop-Only Mode
# ============================================================================

if ($StopOnly) {
    Write-Step "Mencari proses yeehee-daemon..." 'Yellow'
    Get-Process python -ErrorAction SilentlyContinue | Where-Object {
        $_.Path -like "$InstallDir\\*"
    } | ForEach-Object {
        Write-Host "  stopping pid $($_.Id) ($($_.Path))" -ForegroundColor Yellow
        Stop-Process -Id $_.Id -Force
    }
    $svc = Get-Service -Name "${SERVICE_NAME}" -ErrorAction SilentlyContinue
    if ($svc) {
        Write-Host "  stopping service ${SERVICE_NAME}" -ForegroundColor Yellow
        Stop-Service -Name "${SERVICE_NAME}" -Force -ErrorAction SilentlyContinue
    }
    Write-OK "Done."
    exit 0
}

# ============================================================================
# Main Install Flow
# ============================================================================

try {
    Write-Step "yeehee Signal Daemon installer" 'Green'
    Write-Host "  Folder:    $InstallDir"        -ForegroundColor DarkGray
    Write-Host "  Port:      $Port"               -ForegroundColor DarkGray
    Write-Host "  Supabase:  $SupabaseUrl"        -ForegroundColor DarkGray
    Write-Host "  Service:   ${SERVICE_NAME}"     -ForegroundColor DarkGray
    Write-Host "  PS Version: $($PSVersionTable.PSVersion)" -ForegroundColor DarkGray

    # -- Pre-flight: PowerShell version -----------------------------------------
    if ($PSVersionTable.PSVersion.Major -lt 5) {
        throw "PowerShell terlalu lama. Butuh minimum 5.1, lo punya $($PSVersionTable.PSVersion). Update Windows ke 10/11."
    }

    # -- Pre-flight: Supabase reachability + schema check (fail fast) -----------
    # Note: /rest/v1/ root returns 401 even with valid anon key (Supabase quirk).
    # Use a real table query instead - confirms key valid AND schema applied.
    Write-Step "0/7 Validasi koneksi Supabase + schema..."
    try {
        $resp = Invoke-WebRequest -Uri "$SupabaseUrl/rest/v1/app_settings?select=user_id&limit=1" -Headers @{
            "apikey"        = $SupabaseAnonKey
            "Authorization" = "Bearer $SupabaseAnonKey"
        } -UseBasicParsing -TimeoutSec 10 -ErrorAction Stop
        Write-OK "Supabase + schema OK (HTTP $($resp.StatusCode))"
    } catch {
        $statusCode = if ($_.Exception.Response) { $_.Exception.Response.StatusCode.value__ } else { 0 }
        if ($statusCode -eq 401 -or $statusCode -eq 403) {
            throw "Supabase auth gagal (HTTP $statusCode). Cek SUPABASE_ANON_KEY di Vercel env Settings -> Environment Variables."
        } elseif ($statusCode -eq 404) {
            throw "Tabel app_settings tidak ada di Supabase. Project belum di-init / URL salah. URL: $SupabaseUrl"
        } else {
            Write-Warn "Supabase ping gagal: $($_.Exception.Message). Lanjut anyway..."
        }
    }

    # -- Step 1: Python + Git --------------------------------------------------
    Write-Step "1/7 Cek Python 3.10+..."
    Refresh-Path
    if (-not (Test-RealPython)) {
        Write-Warn "Python belum ada (atau cuma MS Store stub). Auto-install..."
        Install-Tool "Python.Python.3.13" "Python 3.13"
        Add-PythonToPath
        Refresh-Path
        if (-not (Test-RealPython)) {
            throw "Python install selesai tapi belum ke-detect. Logout-login Windows lalu run script ulang. (winget kadang butuh re-login untuk PATH propagate.)"
        }
    }
    $pyVer = (& python --version 2>&1) -join ''
    Write-OK "Python OK: $pyVer"

    Write-Step "1.5/7 Cek Git..."
    if (-not (Get-Command git -ErrorAction SilentlyContinue)) {
        Write-Warn "Git belum ada. Auto-install..."
        Install-Tool "Git.Git" "Git"
        Refresh-Path
        if (-not (Get-Command git -ErrorAction SilentlyContinue)) {
            throw "Git install selesai tapi belum ke-detect. Logout-login Windows lalu run ulang."
        }
    }
    $gitVer = (& git --version 2>&1) -join ''
    Write-OK "Git OK: $gitVer"

    # -- Step 2: Clone / pull repo (with retry) ---------------------------------
    Write-Step "2/7 Sync repo yeehee dari GitHub..."
    if (Test-Path "$InstallDir\\.git") {
        Set-Location $InstallDir
        Write-Host "  pulling latest..." -ForegroundColor DarkGray
        Invoke-Native -Cmd "git" -Args @("pull","--rebase","--autostash") -Label "git pull" -Retries 2
    } else {
        if (Test-Path $InstallDir) {
            $bak = "$InstallDir.bak.$(Get-Date -Format 'yyyyMMddHHmmss')"
            Write-Warn "Folder $InstallDir ada tapi bukan git repo - backup ke $bak"
            try {
                Move-Item -Force $InstallDir $bak -ErrorAction Stop
            } catch {
                Write-Warn "Move gagal (mungkin file in-use). Pakai folder dengan suffix timestamp."
                $InstallDir = "$InstallDir-$(Get-Date -Format 'yyyyMMddHHmmss')"
            }
        }
        Write-Host "  cloning..." -ForegroundColor DarkGray
        Invoke-Native -Cmd "git" -Args @("clone","--depth","1","${REPO_URL}",$InstallDir) -Label "git clone" -Retries 2
        Set-Location $InstallDir
    }
    Write-OK "Repo synced"

    # -- Step 3: venv -----------------------------------------------------------
    Write-Step "3/7 Setup Python venv..."
    if (-not (Test-Path "$InstallDir\\.venv\\Scripts\\python.exe")) {
        Invoke-Native -Cmd "python" -Args @("-m","venv",".venv") -Label "python -m venv"
    } else {
        Write-Host "  venv sudah ada, skip" -ForegroundColor DarkGray
    }
    $Py = "$InstallDir\\.venv\\Scripts\\python.exe"
    if (-not (Test-Path $Py)) {
        throw "venv create gagal - $Py tidak ada"
    }
    Write-OK "venv ready"

    # -- Step 4: deps (lean ~80 MB) --------------------------------------------
    Write-Step "4/7 Install Python dependencies (~80 MB)..."
    Write-Host "  Mirror: $PipMirror" -ForegroundColor DarkGray
    Write-Host "  Tip: koneksi lambat? Biarkan retry jalan - pip resume dari posisi terakhir." -ForegroundColor DarkGray
    # Tsinghua mirror default - jauh lebih cepat dari pypi.org untuk Asia/Indonesia (sering 10x)
    # Override dengan -PipMirror "https://pypi.org/simple" kalau mau pakai default upstream.
    $pipFlags = @(
        "--index-url",$PipMirror,
        "--extra-index-url","https://pypi.org/simple",
        "--timeout","300",
        "--retries","20",
        "--prefer-binary",
        "--no-cache-dir",
        "--disable-pip-version-check"
    )
    Invoke-Native -Cmd $Py -Args (@("-m","pip","install","--upgrade","pip") + $pipFlags) -Label "pip upgrade" -Quiet -Retries 1
    Invoke-Native -Cmd $Py -Args (@("-m","pip","install","-r","$InstallDir\\daemon\\requirements.txt") + $pipFlags) -Label "pip install daemon deps" -Retries 3
    Write-OK "deps installed"

    # -- Step 5: write .env -----------------------------------------------------
    Write-Step "5/7 Tulis konfigurasi (.env)..."
    $EnvLines = @(
        "SUPABASE_URL=$SupabaseUrl"
        "SUPABASE_ANON_KEY=$SupabaseAnonKey"
        "DAEMON_USER_ID=$UserId"
        "DAEMON_PORT=$Port"
    )
    $Utf8NoBom = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllLines("$InstallDir\\.env", $EnvLines, $Utf8NoBom)
    Write-OK ".env written"

    # -- Step 6: smoke test daemon imports --------------------------------------
    Write-Step "6/7 Smoke test daemon imports..."
    $smokeArgs = @("-c","import sys; sys.path.insert(0, r'$InstallDir'); from daemon.runner import run_once; from daemon.mira import MiraConsumer; from daemon.heartbeat import push_heartbeat, VERSION; print('daemon v'+VERSION+' import OK')")
    Invoke-Native -Cmd $Py -Args $smokeArgs -Label "smoke test"
    Write-OK "imports valid"

    # -- Step 7a: install service mode ------------------------------------------
    if ($InstallServiceOnly) {
        Write-Step "7/7 Install Windows Service (auto-start saat boot)..." 'Green'

        # Ensure admin
        $isAdmin = ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
        if (-not $isAdmin) {
            throw "Install service butuh PowerShell sebagai Administrator. Klik kanan PowerShell -> Run as Administrator, ulangi."
        }

        if (-not (Get-Command nssm -ErrorAction SilentlyContinue)) {
            Install-Tool "NSSM.NSSM" "NSSM"
            Refresh-Path
        }
        if (-not (Get-Command nssm -ErrorAction SilentlyContinue)) {
            throw "NSSM install gagal."
        }

        # Remove existing service if any
        $svc = Get-Service -Name "${SERVICE_NAME}" -ErrorAction SilentlyContinue
        if ($svc) {
            Write-Warn "service ${SERVICE_NAME} sudah ada, remove dulu"
            Invoke-Native -Cmd "nssm" -Args @("stop","${SERVICE_NAME}","confirm")   -Label "nssm stop"   -Quiet
            Invoke-Native -Cmd "nssm" -Args @("remove","${SERVICE_NAME}","confirm") -Label "nssm remove" -Quiet
        }

        Invoke-Native -Cmd "nssm" -Args @("install","${SERVICE_NAME}",$Py,"-m","daemon.main") -Label "nssm install" -Quiet
        Invoke-Native -Cmd "nssm" -Args @("set","${SERVICE_NAME}","AppDirectory",$InstallDir) -Label "nssm AppDirectory" -Quiet
        Invoke-Native -Cmd "nssm" -Args @("set","${SERVICE_NAME}","DisplayName","yeehee XAU Signal Daemon") -Label "nssm DisplayName" -Quiet
        Invoke-Native -Cmd "nssm" -Args @("set","${SERVICE_NAME}","Description","9-agent LLM signal worker + Mira chatbot consumer") -Label "nssm Description" -Quiet
        Invoke-Native -Cmd "nssm" -Args @("set","${SERVICE_NAME}","Start","SERVICE_AUTO_START") -Label "nssm Start" -Quiet
        Invoke-Native -Cmd "nssm" -Args @("set","${SERVICE_NAME}","AppStdout","$InstallDir\\daemon.log") -Label "nssm AppStdout" -Quiet
        Invoke-Native -Cmd "nssm" -Args @("set","${SERVICE_NAME}","AppStderr","$InstallDir\\daemon.error.log") -Label "nssm AppStderr" -Quiet
        Invoke-Native -Cmd "nssm" -Args @("set","${SERVICE_NAME}","AppRotateFiles","1") -Label "nssm rotate" -Quiet
        Invoke-Native -Cmd "nssm" -Args @("set","${SERVICE_NAME}","AppRotateBytes","10485760") -Label "nssm rotate-bytes" -Quiet

        Start-Service -Name "${SERVICE_NAME}"
        Start-Sleep -Seconds 5
        $svc = Get-Service -Name "${SERVICE_NAME}"
        if ($svc.Status -ne 'Running') {
            throw "Service ${SERVICE_NAME} status = $($svc.Status). Cek $InstallDir\\daemon.error.log"
        }

        Write-Host ""
        Write-Host "============================================================" -ForegroundColor Green
        Write-OK "Service installed & RUNNING."
        Write-Host "============================================================" -ForegroundColor Green
        Write-Host "  Status:  Get-Service ${SERVICE_NAME}"
        Write-Host "  Stop:    Stop-Service ${SERVICE_NAME}"
        Write-Host "  Start:   Start-Service ${SERVICE_NAME}"
        Write-Host "  Logs:    $InstallDir\\daemon.log"
        Write-Host ""
        exit 0
    }

    # -- Step 7b: foreground run ------------------------------------------------
    Write-Step "7/7 Starting daemon (foreground - Ctrl+C kalau mau stop)..." 'Green'
    Write-Host "  Logs: stdout window ini" -ForegroundColor DarkGray
    Write-Host "  Buat auto-start saat boot Windows: ulangi installer dengan flag -InstallServiceOnly (perlu Admin)" -ForegroundColor DarkGray
    Write-Host ""
    Write-Host "============================================================" -ForegroundColor Green
    Write-Host ""

    # Start daemon (this blocks until Ctrl+C)
    & $Py -m daemon.main
}
catch {
    Write-Host ""
    Write-Host "============================================================" -ForegroundColor Red
    Write-Host "[yeehee] [ERROR] Install gagal:" -ForegroundColor Red
    Write-Host "  $($_.Exception.Message)"      -ForegroundColor Red
    Write-Host "============================================================" -ForegroundColor Red
    Write-Host ""
    Write-Host "Detail di atas log warna abu-abu."
    Write-Host "Tekan Enter untuk tutup window..."
    [void](Read-Host)
    exit 1
}
`

export async function GET() {
  // UTF-8 BOM (﻿) so PowerShell 5.1 (default Windows-1252 codepage) auto-detects encoding
  const BOM = '﻿'
  return new NextResponse(BOM + SCRIPT, {
    status: 200,
    headers: {
      'Content-Type':                'text/plain; charset=utf-8',
      'Cache-Control':               'no-store, no-cache, must-revalidate',
      'Content-Disposition':         'inline; filename="yeehee-setup.ps1"',
      'Access-Control-Allow-Origin': '*',
    },
  })
}
