/**
 * GET /api/setup/script
 *
 * Returns a parametrised PowerShell setup script. Pattern matches clinix.id Mira
 * worker - user pastes single-line bootstrap that downloads this script then runs
 * it with secrets passed as named flags. No clipboard-paste fragility.
 *
 * Usage from client (one-liner the user pastes in PowerShell):
 *
 *   Set-ExecutionPolicy -Scope Process Bypass -Force
 *   iwr https://yeehee.vercel.app/api/setup/script -OutFile $env:TEMP\yeehee-setup.ps1
 *   & $env:TEMP\yeehee-setup.ps1 -SupabaseUrl '...' -SupabaseAnonKey '...'
 *
 * The script is generic - secrets are passed at invocation time. The route just
 * serves the script body so it always reflects the latest version on Vercel.
 */
import { NextResponse } from 'next/server'

export const dynamic = 'force-dynamic'   // never cache
export const runtime  = 'edge'

const REPO_URL    = 'https://github.com/proreyhanwijaya111/yeehee.git'
const DEFAULT_DIR = 'yeehee-daemon'
const DEFAULT_PORT = '3031'
const SERVICE_NAME = 'yeehee-signal-daemon'

const SCRIPT = `# yeehee Signal Daemon - installer (auto-generated by yeehee.vercel.app)
# Worker terpisah dari Mira WA Worker (Clinix). Folder: $HOME\\${DEFAULT_DIR}, port ${DEFAULT_PORT}.

[CmdletBinding()]
param(
    [Parameter(Mandatory=$true)]  [string] $SupabaseUrl,
    [Parameter(Mandatory=$true)]  [string] $SupabaseAnonKey,
    [Parameter(Mandatory=$false)] [string] $UserId      = "default",
    [Parameter(Mandatory=$false)] [string] $Port        = "${DEFAULT_PORT}",
    [Parameter(Mandatory=$false)] [string] $InstallDir  = "$HOME\\${DEFAULT_DIR}",
    [Parameter(Mandatory=$false)] [switch] $InstallServiceOnly,
    [Parameter(Mandatory=$false)] [switch] $StopOnly
)

$ErrorActionPreference = 'Stop'
$VerbosePreference     = 'SilentlyContinue'

function Write-Step ($Msg, $Color = 'Cyan') {
    Write-Host ""
    Write-Host "[yeehee] $Msg" -ForegroundColor $Color
}

function Refresh-Path {
    $env:PATH = [Environment]::GetEnvironmentVariable("PATH", "Machine") + ";" +
                [Environment]::GetEnvironmentVariable("PATH", "User")
}

function Ensure-Tool {
    param([string]$Cmd, [string]$WingetId, [string]$Label)
    if (Get-Command $Cmd -ErrorAction SilentlyContinue) { return }
    Write-Step "$Label belum terinstall - auto-install via winget..." 'Yellow'
    try {
        winget install --id $WingetId -e --accept-source-agreements --accept-package-agreements --silent | Out-Null
    } catch {
        throw "Gagal install $Label via winget. Pastikan Windows 10/11 + winget tersedia. Error: $_"
    }
    Refresh-Path
    if (-not (Get-Command $Cmd -ErrorAction SilentlyContinue)) {
        throw "$Label terinstall tapi belum ke-detect di PATH. Logout-login Windows lalu jalankan ulang."
    }
}

# -- Stop only mode ------------------------------------------------------------
if ($StopOnly) {
    Write-Step "Mencari proses yeehee-daemon..." 'Yellow'
    Get-Process python -ErrorAction SilentlyContinue | Where-Object {
        $_.Path -like "$InstallDir\\*"
    } | ForEach-Object {
        Write-Host "  stopping pid $($_.Id) ($($_.Path))" -ForegroundColor Yellow
        Stop-Process -Id $_.Id -Force
    }
    Get-Service -Name "${SERVICE_NAME}" -ErrorAction SilentlyContinue | ForEach-Object {
        Write-Host "  stopping service ${SERVICE_NAME}" -ForegroundColor Yellow
        Stop-Service -Name "${SERVICE_NAME}" -Force
    }
    Write-Host "[yeehee] Done." -ForegroundColor Green
    exit 0
}

try {
    Write-Step "yeehee Signal Daemon installer" 'Green'
    Write-Host "  Folder:   $InstallDir"        -ForegroundColor DarkGray
    Write-Host "  Port:     $Port"               -ForegroundColor DarkGray
    Write-Host "  Supabase: $SupabaseUrl"        -ForegroundColor DarkGray
    Write-Host "  Service:  ${SERVICE_NAME}"     -ForegroundColor DarkGray

    # -- Step 1: Ensure Python + Git ------------------------------------------
    Write-Step "1/6 Cek dependency (Python + Git)..."
    Refresh-Path
    Ensure-Tool python  Python.Python.3.13  "Python 3.13"
    Ensure-Tool git     Git.Git             "Git"

    # -- Step 2: Clone / pull repo --------------------------------------------
    Write-Step "2/6 Sync repo yeehee..."
    if (Test-Path "$InstallDir\\.git") {
        Set-Location $InstallDir
        Write-Host "  pulling latest..." -ForegroundColor DarkGray
        git pull --rebase --autostash 2>&1 | Out-Null
    } else {
        if (Test-Path $InstallDir) {
            Write-Host "  folder ada tapi bukan git repo - backup ke $InstallDir.bak" -ForegroundColor Yellow
            Move-Item -Force $InstallDir "$InstallDir.bak.$(Get-Date -Format 'yyyyMMddHHmmss')"
        }
        git clone --depth 1 ${REPO_URL} $InstallDir 2>&1 | Out-Null
        Set-Location $InstallDir
    }

    # -- Step 3: venv ---------------------------------------------------------
    Write-Step "3/6 Setup Python venv..."
    if (-not (Test-Path "$InstallDir\\.venv\\Scripts\\python.exe")) {
        python -m venv .venv
    } else {
        Write-Host "  venv sudah ada, skip" -ForegroundColor DarkGray
    }
    $Py = "$InstallDir\\.venv\\Scripts\\python.exe"

    # -- Step 4: deps (lean daemon requirements) -----------------------------
    Write-Step "4/6 Install Python dependencies (~2-4 min sekali aja)..."
    & $Py -m pip install --upgrade pip --quiet 2>&1 | Out-Null
    & $Py -m pip install -r "$InstallDir\\daemon\\requirements.txt" --quiet 2>&1 | Out-Null
    Write-Host "  done." -ForegroundColor DarkGray

    # -- Step 5: write .env (atomic, UTF-8 no BOM) ---------------------------
    Write-Step "5/6 Tulis konfigurasi (.env)..."
    $EnvLines = @(
        "SUPABASE_URL=$SupabaseUrl"
        "SUPABASE_ANON_KEY=$SupabaseAnonKey"
        "DAEMON_USER_ID=$UserId"
        "DAEMON_PORT=$Port"
    )
    $Utf8NoBom = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllLines("$InstallDir\\.env", $EnvLines, $Utf8NoBom)
    Write-Host "  $InstallDir\\.env written" -ForegroundColor DarkGray

    # -- Step 6: install service (optional) or run foreground ----------------
    if ($InstallServiceOnly) {
        Write-Step "6/6 Install Windows Service (auto-start saat boot)..."
        Ensure-Tool nssm NSSM.NSSM "NSSM"

        # remove existing service if any
        $svc = Get-Service -Name "${SERVICE_NAME}" -ErrorAction SilentlyContinue
        if ($svc) {
            Write-Host "  service sudah ada - remove dulu" -ForegroundColor Yellow
            nssm stop "${SERVICE_NAME}"   confirm 2>&1 | Out-Null
            nssm remove "${SERVICE_NAME}" confirm 2>&1 | Out-Null
        }

        nssm install "${SERVICE_NAME}" $Py -m daemon.main          | Out-Null
        nssm set "${SERVICE_NAME}" AppDirectory   $InstallDir       | Out-Null
        nssm set "${SERVICE_NAME}" DisplayName    "yeehee XAU Signal Daemon" | Out-Null
        nssm set "${SERVICE_NAME}" Description    "9-agent LLM signal worker + Mira chatbot consumer (separate from Mira WA Worker)" | Out-Null
        nssm set "${SERVICE_NAME}" Start          SERVICE_AUTO_START | Out-Null
        nssm set "${SERVICE_NAME}" AppStdout      "$InstallDir\\daemon.log"        | Out-Null
        nssm set "${SERVICE_NAME}" AppStderr      "$InstallDir\\daemon.error.log"  | Out-Null
        nssm set "${SERVICE_NAME}" AppRotateFiles 1                 | Out-Null
        nssm set "${SERVICE_NAME}" AppRotateBytes 10485760           | Out-Null

        net start "${SERVICE_NAME}" | Out-Null
        Write-Host ""
        Write-Host "[yeehee] [OK] Service installed & started." -ForegroundColor Green
        Write-Host "    Status: net query ${SERVICE_NAME}"
        Write-Host "    Stop:   net stop ${SERVICE_NAME}"
        Write-Host "    Logs:   $InstallDir\\daemon.log"
        exit 0
    }

    Write-Step "6/6 Starting daemon (foreground - Ctrl+C kalau mau stop)..." 'Green'
    Write-Host "  Logs: stdout window ini" -ForegroundColor DarkGray
    Write-Host "  Buat auto-start saat boot: jalankan installer dengan flag -InstallServiceOnly (perlu Admin)"
    Write-Host ""
    & $Py -m daemon.main
}
catch {
    Write-Host ""
    Write-Host "[yeehee] [ERROR] ERROR: $_" -ForegroundColor Red
    Write-Host ""
    Write-Host "Tekan Enter untuk tutup window..."
    [void](Read-Host)
    exit 1
}
`

export async function GET() {
  // Prefix with UTF-8 BOM so Windows PowerShell 5.1 auto-detects encoding
  // (without BOM, PS5.1 falls back to system codepage / Windows-1252 and mis-reads
  // any non-ASCII byte). Even though we now ASCII-clean the body, BOM is a free
  // safety net for future content.
  const BOM = '﻿'
  return new NextResponse(BOM + SCRIPT, {
    status: 200,
    headers: {
      'Content-Type':                'text/plain; charset=utf-8',
      'Cache-Control':               'no-store, no-cache, must-revalidate',
      'Content-Disposition':         'inline; filename="yeehee-setup.ps1"',
      'Access-Control-Allow-Origin': '*',
    },
  })
}
