/**
 * GET /api/setup/script
 *
 * Returns the bulletproof PowerShell installer for the yeehee Signal Daemon.
 * Pattern matches clinix.id Mira worker - user pastes a single-line bootstrap
 * that downloads this script, runs it with named flags. No clipboard fragility.
 *
 * Defensive against every realistic failure on a fresh Windows PC:
 *  - PowerShell 5.1 native-cmd stderr quirk (Invoke-Native helper)
 *  - MS Store Python alias detection
 *  - Missing winget (clear error message + manual instructions)
 *  - Network retry for git / pip
 *  - Supabase reachability check pre-install (fail fast on bad creds)
 *  - Post-launch daemon liveness verify
 *  - ASCII-only body + UTF-8 BOM (PS 5.1 codepage compat)
 */
import { NextResponse } from 'next/server'

export const dynamic = 'force-dynamic'
export const runtime  = 'edge'

const REPO_URL    = 'https://github.com/proreyhanwijaya111/yeehee.git'
const DEFAULT_DIR = 'yeehee-daemon'
const DEFAULT_PORT = '3031'
const SERVICE_NAME = 'yeehee-signal-daemon'

const SCRIPT = `# yeehee Signal Daemon - bulletproof installer (auto-generated by yeehee.vercel.app)
# Worker terpisah dari Mira WA Worker (Clinix). Folder: $HOME\\${DEFAULT_DIR}, port ${DEFAULT_PORT}.
#
# v2 changes (multi-PC ready):
#  - Optional service-role key (lebih reliable kalau RLS aktif)
#  - OpenRouter LLM key (biar 12-agent LLM langsung jalan, bukan rule fallback)
#  - Twelve Data key (real-time XAU spot price, bukan yfinance 15min delay)
#  - Auto-generate WorkerId (UUID) per install — foundation buat multi-PC failover
#  - Idempotent .env: kalau .env sudah ada di disk, preserve nilai yang ga di-override

[CmdletBinding()]
param(
    [Parameter(Mandatory=$true)]  [string] $SupabaseUrl,
    [Parameter(Mandatory=$true)]  [string] $SupabaseAnonKey,
    [Parameter(Mandatory=$false)] [string] $SupabaseServiceKey = "",
    [Parameter(Mandatory=$false)] [string] $OpenRouterKey      = "",
    [Parameter(Mandatory=$false)] [string] $TwelveDataKey      = "",
    [Parameter(Mandatory=$false)] [string] $UserId      = "default",
    [Parameter(Mandatory=$false)] [string] $Port        = "${DEFAULT_PORT}",
    [Parameter(Mandatory=$false)] [string] $WorkerId    = "",
    [Parameter(Mandatory=$false)] [string] $InstallDir  = "$HOME\\${DEFAULT_DIR}",
    [Parameter(Mandatory=$false)] [string] $PipMirror   = "https://pypi.tuna.tsinghua.edu.cn/simple",
    # Mode flags - DEFAULT now = install as Service (production-ready 24/7).
    # Pakai -Foreground kalau mau debug/testing dengan log live di window.
    [Parameter(Mandatory=$false)] [switch] $Foreground,
    [Parameter(Mandatory=$false)] [switch] $InstallServiceOnly,  # alias backwards-compat
    [Parameter(Mandatory=$false)] [switch] $StopOnly
)

# Auto-generate WorkerId (UUID, first 8 chars of hostname-uuid) kalau ga di-set
if (-not $WorkerId -or $WorkerId.Trim() -eq "") {
    $hostShort = ($env:COMPUTERNAME -replace '[^a-zA-Z0-9]', '').ToLower()
    if ($hostShort.Length -gt 8) { $hostShort = $hostShort.Substring(0,8) }
    $uuidShort = ([guid]::NewGuid().ToString() -replace '-','').Substring(0,6)
    $WorkerId = "$hostShort-$uuidShort"
}

# Determine final mode: Service (default) vs Foreground (testing).
# -InstallServiceOnly is now redundant (Service is default) but kept for backwards compat.
$IsServiceMode = -not $Foreground.IsPresent

# Use 'Continue' to avoid PS 5.1 native-cmd stderr quirk. We check exit codes manually.
$ErrorActionPreference = 'Continue'
$VerbosePreference     = 'SilentlyContinue'
$ProgressPreference    = 'SilentlyContinue'

# -- Network: force TLS 1.2+ (PS 5.1 default mau pakai TLS 1.0 yang sudah ditolak banyak server) --
try {
    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12 -bor [Net.SecurityProtocolType]::Tls13
} catch {
    try { [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12 } catch {}
}

# -- Console: switch ke UTF-8 supaya text Indonesia ga rusak --
try { chcp 65001 > $null 2>&1 } catch {}
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8

# -- Git: jangan prompt credential (repo public, ga butuh login) --
$env:GIT_TERMINAL_PROMPT  = '0'
$env:GIT_ASKPASS          = 'echo'
$env:GCM_INTERACTIVE      = 'never'

# ============================================================================
# Helpers
# ============================================================================

function Write-Step ($Msg, $Color = 'Cyan') {
    Write-Host ""
    Write-Host "[yeehee] $Msg" -ForegroundColor $Color
}

function Write-OK ($Msg) {
    Write-Host "  [OK] $Msg" -ForegroundColor Green
}

function Write-Warn ($Msg) {
    Write-Host "  [WARN] $Msg" -ForegroundColor Yellow
}

function Refresh-Path {
    $env:PATH = [Environment]::GetEnvironmentVariable("PATH", "Machine") + ";" +
                [Environment]::GetEnvironmentVariable("PATH", "User")
}

# Native-cmd wrapper: captures exit code without falling for PS 5.1 stderr quirk.
function Invoke-Native {
    param(
        [Parameter(Mandatory)] [string]   $Cmd,
        [Parameter(Mandatory)] [string[]] $Args,
        [string] $Label = $Cmd,
        [switch] $Quiet,
        [int]    $Retries = 0
    )
    $attempt = 0
    while ($true) {
        $attempt++
        if ($Quiet) {
            & $Cmd @Args *>$null
        } else {
            & $Cmd @Args 2>&1 | ForEach-Object { Write-Host "    $_" -ForegroundColor DarkGray }
        }
        $code = $LASTEXITCODE
        if ($code -eq 0) { return }
        if ($attempt -gt $Retries) {
            throw "$Label failed (exit code $code)"
        }
        Write-Warn "$Label exit $code, retry $attempt/$Retries dalam 3 detik..."
        Start-Sleep -Seconds 3
    }
}

# Detect MS Store Python alias (Win11 ships a stub python.exe that opens Store).
function Test-RealPython {
    $py = Get-Command python -ErrorAction SilentlyContinue
    if (-not $py) { return $false }
    # MS Store stub lives under WindowsApps and reports 0-byte length when queried via Get-Item
    if ($py.Source -like "*WindowsApps*") {
        try {
            $size = (Get-Item $py.Source -ErrorAction Stop).Length
            if ($size -lt 100KB) { return $false }
        } catch {
            return $false
        }
    }
    # Try to actually run it
    try {
        $ver = & python --version 2>&1
        if ($LASTEXITCODE -ne 0) { return $false }
        return ($ver -match 'Python 3\\.(1[0-9]|[2-9][0-9])')   # 3.10+
    } catch {
        return $false
    }
}

function Test-Winget {
    return [bool](Get-Command winget -ErrorAction SilentlyContinue)
}

function Install-Tool {
    param([string]$WingetId, [string]$Label)
    if (-not (Test-Winget)) {
        throw "winget tidak tersedia. Update Windows ke 10 1809+ / 11, atau install $Label manual dulu."
    }
    Write-Host "  installing $Label via winget..." -ForegroundColor Yellow
    & winget install --id $WingetId -e --accept-source-agreements --accept-package-agreements --silent --disable-interactivity 2>&1 |
        ForEach-Object { Write-Host "    $_" -ForegroundColor DarkGray }
    Refresh-Path
}

# Add common Python install dirs to PATH (winget user-scope sometimes does not propagate)
function Add-PythonToPath {
    $candidates = @(
        "$env:LOCALAPPDATA\\Programs\\Python\\Python313",
        "$env:LOCALAPPDATA\\Programs\\Python\\Python313\\Scripts",
        "$env:LOCALAPPDATA\\Programs\\Python\\Python312",
        "$env:LOCALAPPDATA\\Programs\\Python\\Python312\\Scripts",
        "C:\\Python313", "C:\\Python313\\Scripts",
        "C:\\Python312", "C:\\Python312\\Scripts"
    )
    foreach ($dir in $candidates) {
        if ((Test-Path $dir) -and ($env:PATH -notlike "*$dir*")) {
            $env:PATH = "$dir;$env:PATH"
        }
    }
}

# ============================================================================
# Stop-Only Mode
# ============================================================================

if ($StopOnly) {
    Write-Step "Mencari proses yeehee-daemon..." 'Yellow'
    Get-Process python -ErrorAction SilentlyContinue | Where-Object {
        $_.Path -like "$InstallDir\\*"
    } | ForEach-Object {
        Write-Host "  stopping pid $($_.Id) ($($_.Path))" -ForegroundColor Yellow
        Stop-Process -Id $_.Id -Force
    }
    $svc = Get-Service -Name "${SERVICE_NAME}" -ErrorAction SilentlyContinue
    if ($svc) {
        Write-Host "  stopping service ${SERVICE_NAME}" -ForegroundColor Yellow
        Stop-Service -Name "${SERVICE_NAME}" -Force -ErrorAction SilentlyContinue
    }
    Write-OK "Done."
    exit 0
}

# ============================================================================
# Main Install Flow
# ============================================================================

try {
    $modeLabel = if ($IsServiceMode) { "Service (auto-start 24/7)" } else { "Foreground (debug)" }
    $modeColor = if ($IsServiceMode) { "Green" } else { "Yellow" }
    Write-Step "yeehee Signal Daemon installer" 'Green'
    Write-Host "  Mode:      $modeLabel" -ForegroundColor $modeColor
    Write-Host "  Folder:    $InstallDir"        -ForegroundColor DarkGray
    Write-Host "  Port:      $Port"               -ForegroundColor DarkGray
    Write-Host "  Supabase:  $SupabaseUrl"        -ForegroundColor DarkGray
    Write-Host "  Service:   ${SERVICE_NAME}"     -ForegroundColor DarkGray
    Write-Host "  PS Version: $($PSVersionTable.PSVersion)" -ForegroundColor DarkGray

    # -- Pre-flight: Admin check (Service mode butuh Admin untuk NSSM) --------
    if ($IsServiceMode) {
        $isAdmin = ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
        if (-not $isAdmin) {
            Write-Host ""
            Write-Host "[yeehee] Service mode butuh Administrator untuk register Windows Service." -ForegroundColor Yellow
            Write-Host ""
            Write-Host "Pilihan lo:" -ForegroundColor Yellow
            Write-Host "  1. Tutup window ini, klik kanan PowerShell -> Run as Administrator, paste lagi." -ForegroundColor White
            Write-Host "  2. Atau pakai -Foreground flag untuk testing (no auto-start, mati saat tutup window)." -ForegroundColor White
            Write-Host ""
            Write-Host "Recommended: pilih 1 buat production 24/7." -ForegroundColor Cyan
            Write-Host ""
            throw "Bukan Administrator. Re-run as Admin atau pakai -Foreground."
        }
    }

    # -- Pre-flight: PowerShell version -----------------------------------------
    if ($PSVersionTable.PSVersion.Major -lt 5) {
        throw "PowerShell terlalu lama. Butuh minimum 5.1, lo punya $($PSVersionTable.PSVersion). Update Windows ke 10/11."
    }

    # -- Pre-flight: Supabase reachability + schema check (fail fast) -----------
    # Note: /rest/v1/ root returns 401 even with valid anon key (Supabase quirk).
    # Use a real table query instead - confirms key valid AND schema applied.
    Write-Step "0/7 Validasi koneksi Supabase + schema..."
    try {
        $resp = Invoke-WebRequest -Uri "$SupabaseUrl/rest/v1/app_settings?select=user_id&limit=1" -Headers @{
            "apikey"        = $SupabaseAnonKey
            "Authorization" = "Bearer $SupabaseAnonKey"
        } -UseBasicParsing -TimeoutSec 10 -ErrorAction Stop
        Write-OK "Supabase + schema OK (HTTP $($resp.StatusCode))"
    } catch {
        $statusCode = if ($_.Exception.Response) { $_.Exception.Response.StatusCode.value__ } else { 0 }
        if ($statusCode -eq 401 -or $statusCode -eq 403) {
            throw "Supabase auth gagal (HTTP $statusCode). Cek SUPABASE_ANON_KEY di Vercel env Settings -> Environment Variables."
        } elseif ($statusCode -eq 404) {
            throw "Tabel app_settings tidak ada di Supabase. Project belum di-init / URL salah. URL: $SupabaseUrl"
        } else {
            Write-Warn "Supabase ping gagal: $($_.Exception.Message). Lanjut anyway..."
        }
    }

    # -- Step 1: Python + Git --------------------------------------------------
    Write-Step "1/7 Cek Python 3.10+..."
    Refresh-Path
    if (-not (Test-RealPython)) {
        Write-Warn "Python belum ada / cuma MS Store stub. Auto-install..."
        # Try Python 3.13, fallback to 3.12 (some Windows versions don't have 3.13 in winget)
        $pyInstalled = $false
        foreach ($pyId in @("Python.Python.3.13","Python.Python.3.12","Python.Python.3.11")) {
            try {
                Install-Tool $pyId "Python ($pyId)"
                Add-PythonToPath
                Refresh-Path
                if (Test-RealPython) {
                    $pyInstalled = $true
                    break
                }
            } catch {
                Write-Warn "$pyId install gagal: $($_.Exception.Message). Coba versi lain..."
            }
        }
        if (-not $pyInstalled) {
            throw "Python install gagal di semua versi (3.13/3.12/3.11). Coba install manual dari python.org lalu run ulang script."
        }
    }
    $pyVer = (& python --version 2>&1) -join ''
    Write-OK "Python: $pyVer"

    Write-Step "1.5/7 Cek Git..."
    if (-not (Get-Command git -ErrorAction SilentlyContinue)) {
        Write-Warn "Git belum ada. Auto-install..."
        Install-Tool "Git.Git" "Git"
        Refresh-Path
        if (-not (Get-Command git -ErrorAction SilentlyContinue)) {
            throw "Git install selesai tapi belum ke-detect PATH. Logout-login Windows lalu run script ulang. (winget kadang butuh re-login untuk PATH propagate.)"
        }
    }
    $gitVer = (& git --version 2>&1) -join ''
    Write-OK "Git: $gitVer"

    # -- Step 2: Clone / pull repo (with retry) ---------------------------------
    Write-Step "2/7 Sync repo yeehee dari GitHub..."
    if (Test-Path "$InstallDir\\.git") {
        Set-Location $InstallDir
        Write-Host "  pulling latest..." -ForegroundColor DarkGray
        Invoke-Native -Cmd "git" -Args @("pull","--rebase","--autostash") -Label "git pull" -Retries 2
    } else {
        if (Test-Path $InstallDir) {
            $bak = "$InstallDir.bak.$(Get-Date -Format 'yyyyMMddHHmmss')"
            Write-Warn "Folder $InstallDir ada tapi bukan git repo - backup ke $bak"
            try {
                Move-Item -Force $InstallDir $bak -ErrorAction Stop
            } catch {
                Write-Warn "Move gagal (mungkin file in-use). Pakai folder dengan suffix timestamp."
                $InstallDir = "$InstallDir-$(Get-Date -Format 'yyyyMMddHHmmss')"
            }
        }
        Write-Host "  cloning..." -ForegroundColor DarkGray
        Invoke-Native -Cmd "git" -Args @("clone","--depth","1","${REPO_URL}",$InstallDir) -Label "git clone" -Retries 2
        Set-Location $InstallDir
    }
    Write-OK "Repo synced"

    # -- Step 3: venv (cleanup-on-fail + retry + ensurepip) --------------------
    Write-Step "3/7 Setup Python venv..."
    $Py = "$InstallDir\\.venv\\Scripts\\python.exe"
    if (-not (Test-Path $Py)) {
        try {
            Invoke-Native -Cmd "python" -Args @("-m","venv",".venv") -Label "python -m venv" -Quiet
        } catch {
            Write-Warn "venv create gagal: $($_.Exception.Message). Cleanup + retry..."
            if (Test-Path "$InstallDir\\.venv") {
                Remove-Item -Recurse -Force "$InstallDir\\.venv" -ErrorAction SilentlyContinue
            }
            Invoke-Native -Cmd "python" -Args @("-m","venv",".venv","--clear") -Label "python -m venv (retry --clear)" -Quiet
        }
    } else {
        Write-Host "  venv sudah ada, skip" -ForegroundColor DarkGray
    }
    if (-not (Test-Path $Py)) {
        throw "venv create gagal - $Py ga ada. Coba: python --version (cek Python OK), python -m venv .venv (cek venv module)"
    }
    # Make sure pip in venv works (kadang fresh venv ga punya pip working)
    & $Py -m ensurepip --upgrade 2>&1 | Out-Null
    Write-OK "venv ready"

    # -- Step 4: deps (lean ~80 MB) --------------------------------------------
    Write-Step "4/7 Install Python dependencies (~80 MB)..."
    Write-Host "  Mirror: $PipMirror" -ForegroundColor DarkGray
    Write-Host "  Tip: koneksi lambat? Biarkan retry jalan - pip resume dari posisi terakhir." -ForegroundColor DarkGray
    # Tsinghua mirror default - jauh lebih cepat dari pypi.org untuk Asia/Indonesia (sering 10x)
    # Override dengan -PipMirror "https://pypi.org/simple" kalau mau pakai default upstream.
    $pipFlags = @(
        "--index-url",$PipMirror,
        "--extra-index-url","https://pypi.org/simple",
        "--timeout","300",
        "--retries","20",
        "--prefer-binary",
        "--no-cache-dir",
        "--disable-pip-version-check"
    )
    Invoke-Native -Cmd $Py -Args (@("-m","pip","install","--upgrade","pip") + $pipFlags) -Label "pip upgrade" -Quiet -Retries 1
    Invoke-Native -Cmd $Py -Args (@("-m","pip","install","-r","$InstallDir\\daemon\\requirements.txt") + $pipFlags) -Label "pip install daemon deps" -Retries 3
    Write-OK "deps installed"

    # -- Step 5: write .env -----------------------------------------------------
    Write-Step "5/7 Tulis konfigurasi (.env)..."
    # IDEMPOTENT: kalau .env sudah ada (re-run installer), preserve nilai yang ga di-override.
    # Param di CLI > nilai existing di .env > default kosong.
    $envPath  = "$InstallDir\\.env"
    $existing = @{}
    if (Test-Path $envPath) {
        # Read with utf-8-sig agar BOM dari editor lama ke-strip otomatis
        $bytes = [System.IO.File]::ReadAllBytes($envPath)
        $text  = [System.Text.UTF8Encoding]::new($false).GetString($bytes).TrimStart([char]0xFEFF)
        foreach ($line in ($text -split "\`r?\`n")) {
            $line = $line.Trim()
            if (-not $line -or $line.StartsWith("#")) { continue }
            $eq = $line.IndexOf("=")
            if ($eq -lt 1) { continue }
            $k = $line.Substring(0, $eq).Trim()
            $v = $line.Substring($eq + 1).Trim()
            if ($k) { $existing[$k] = $v }
        }
        Write-Host "  found existing .env with $($existing.Count) vars, will preserve unspecified" -ForegroundColor DarkGray
    }

    # Helper: pakai param kalau di-pass, fallback ke existing, fallback ke kosong
    function Resolve-EnvValue($paramVal, $key) {
        if ($paramVal -and $paramVal.Trim() -ne "") { return $paramVal.Trim() }
        if ($existing.ContainsKey($key)) { return $existing[$key] }
        return ""
    }

    $finalSupaUrl    = Resolve-EnvValue $SupabaseUrl        "SUPABASE_URL"
    $finalSupaAnon   = Resolve-EnvValue $SupabaseAnonKey    "SUPABASE_ANON_KEY"
    $finalSupaSvc    = Resolve-EnvValue $SupabaseServiceKey "SUPABASE_SERVICE_KEY"
    $finalOpenRouter = Resolve-EnvValue $OpenRouterKey      "OPENROUTER_API_KEY"
    $finalTwelve     = Resolve-EnvValue $TwelveDataKey      "TWELVE_DATA_API_KEY"
    $finalUserId     = Resolve-EnvValue $UserId             "DAEMON_USER_ID"
    $finalPort       = Resolve-EnvValue $Port               "DAEMON_PORT"
    $finalWorkerId   = Resolve-EnvValue $WorkerId           "DAEMON_WORKER_ID"

    # Build env lines — only include ones with values, in deterministic order
    $EnvLines = New-Object System.Collections.ArrayList
    [void]$EnvLines.Add("# yeehee daemon .env — auto-generated by installer. Edit at your own risk.")
    [void]$EnvLines.Add("# Re-run installer to update; existing vars preserved unless explicitly overridden.")
    [void]$EnvLines.Add("")
    [void]$EnvLines.Add("# Supabase (REQUIRED)")
    [void]$EnvLines.Add("SUPABASE_URL=$finalSupaUrl")
    [void]$EnvLines.Add("SUPABASE_ANON_KEY=$finalSupaAnon")
    if ($finalSupaSvc) {
        [void]$EnvLines.Add("SUPABASE_SERVICE_KEY=$finalSupaSvc")
    } else {
        [void]$EnvLines.Add("# SUPABASE_SERVICE_KEY=  # recommended for production (RLS bypass for daemon writes)")
    }
    [void]$EnvLines.Add("")
    [void]$EnvLines.Add("# Daemon identity")
    [void]$EnvLines.Add("DAEMON_USER_ID=$finalUserId")
    [void]$EnvLines.Add("DAEMON_PORT=$finalPort")
    [void]$EnvLines.Add("DAEMON_WORKER_ID=$finalWorkerId")
    [void]$EnvLines.Add("")
    [void]$EnvLines.Add("# LLM provider (OpenRouter — gratis tier 200 req/day)")
    [void]$EnvLines.Add("# Tanpa key: daemon fall back ke rule_engine 4-agent (limited).")
    if ($finalOpenRouter) {
        [void]$EnvLines.Add("OPENROUTER_API_KEY=$finalOpenRouter")
    } else {
        [void]$EnvLines.Add("# OPENROUTER_API_KEY=  # daftar di https://openrouter.ai/keys (gratis)")
    }
    [void]$EnvLines.Add("")
    [void]$EnvLines.Add("# Real-time XAU/USD spot price (Twelve Data — gratis tier 800 req/day)")
    [void]$EnvLines.Add("# Tanpa key: daemon pakai yfinance close (15min delay).")
    if ($finalTwelve) {
        [void]$EnvLines.Add("TWELVE_DATA_API_KEY=$finalTwelve")
    } else {
        [void]$EnvLines.Add("# TWELVE_DATA_API_KEY=  # daftar di https://twelvedata.com (gratis)")
    }

    $Utf8NoBom = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllLines($envPath, [string[]]$EnvLines, $Utf8NoBom)

    # Verify dotenv bisa load semua REQUIRED vars
    $verifyArgs = @("-c","import os, sys; from dotenv import load_dotenv; load_dotenv(); req=['SUPABASE_URL','SUPABASE_ANON_KEY']; missing=[k for k in req if not os.environ.get(k)]; sys.exit(1 if missing else 0); print('OK')")
    Push-Location $InstallDir
    try {
        Invoke-Native -Cmd $Py -Args $verifyArgs -Label "verify .env load" -Quiet
    } finally {
        Pop-Location
    }
    Write-OK ".env written + dotenv verified ($($EnvLines.Count) lines, worker_id=$finalWorkerId)"

    # Status report — apa yang aktif vs warning
    if (-not $finalOpenRouter) {
        Write-Warn "OPENROUTER_API_KEY belum di-set. Daemon akan fall back ke rule_engine 4-agent (no LLM)."
        Write-Host "  Untuk full 12-agent LLM: edit $envPath, tambah OPENROUTER_API_KEY=sk-or-..." -ForegroundColor DarkGray
    }
    if (-not $finalTwelve) {
        Write-Warn "TWELVE_DATA_API_KEY belum di-set. XAU spot pakai yfinance fallback (15min delay)."
    }

    # -- Step 6: smoke test daemon imports --------------------------------------
    Write-Step "6/7 Smoke test daemon imports..."
    $smokeArgs = @("-c","import sys; sys.path.insert(0, r'$InstallDir'); from daemon.runner import run_once; from daemon.mira import MiraConsumer; from daemon.heartbeat import push_heartbeat, VERSION; print('daemon v'+VERSION+' import OK')")
    Invoke-Native -Cmd $Py -Args $smokeArgs -Label "smoke test"
    Write-OK "imports valid"

    # -- Step 7a: install service mode (DEFAULT) -------------------------------
    if ($IsServiceMode -or $InstallServiceOnly) {
        Write-Step "7/7 Install Windows Service (auto-start saat boot)..." 'Green'

        # Ensure admin
        $isAdmin = ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
        if (-not $isAdmin) {
            throw "Install service butuh PowerShell sebagai Administrator. Klik kanan PowerShell -> Run as Administrator, ulangi."
        }

        if (-not (Get-Command nssm -ErrorAction SilentlyContinue)) {
            Install-Tool "NSSM.NSSM" "NSSM"
            Refresh-Path
        }
        if (-not (Get-Command nssm -ErrorAction SilentlyContinue)) {
            throw "NSSM install gagal."
        }

        # Remove existing service if any
        $svc = Get-Service -Name "${SERVICE_NAME}" -ErrorAction SilentlyContinue
        if ($svc) {
            Write-Warn "service ${SERVICE_NAME} sudah ada, remove dulu"
            Invoke-Native -Cmd "nssm" -Args @("stop","${SERVICE_NAME}","confirm")   -Label "nssm stop"   -Quiet
            Invoke-Native -Cmd "nssm" -Args @("remove","${SERVICE_NAME}","confirm") -Label "nssm remove" -Quiet
        }

        Invoke-Native -Cmd "nssm" -Args @("install","${SERVICE_NAME}",$Py,"-m","daemon.main") -Label "nssm install" -Quiet
        Invoke-Native -Cmd "nssm" -Args @("set","${SERVICE_NAME}","AppDirectory",$InstallDir) -Label "nssm AppDirectory" -Quiet
        Invoke-Native -Cmd "nssm" -Args @("set","${SERVICE_NAME}","DisplayName","yeehee XAU Signal Daemon") -Label "nssm DisplayName" -Quiet
        Invoke-Native -Cmd "nssm" -Args @("set","${SERVICE_NAME}","Description","9-agent LLM signal worker + Mira chatbot consumer") -Label "nssm Description" -Quiet
        Invoke-Native -Cmd "nssm" -Args @("set","${SERVICE_NAME}","Start","SERVICE_AUTO_START") -Label "nssm Start" -Quiet
        Invoke-Native -Cmd "nssm" -Args @("set","${SERVICE_NAME}","AppStdout","$InstallDir\\daemon.log") -Label "nssm AppStdout" -Quiet
        Invoke-Native -Cmd "nssm" -Args @("set","${SERVICE_NAME}","AppStderr","$InstallDir\\daemon.error.log") -Label "nssm AppStderr" -Quiet
        Invoke-Native -Cmd "nssm" -Args @("set","${SERVICE_NAME}","AppRotateFiles","1") -Label "nssm rotate" -Quiet
        Invoke-Native -Cmd "nssm" -Args @("set","${SERVICE_NAME}","AppRotateBytes","10485760") -Label "nssm rotate-bytes" -Quiet

        Start-Service -Name "${SERVICE_NAME}"
        Start-Sleep -Seconds 5
        $svc = Get-Service -Name "${SERVICE_NAME}"
        if ($svc.Status -ne 'Running') {
            throw "Service ${SERVICE_NAME} status = $($svc.Status). Cek $InstallDir\\daemon.error.log"
        }

        Write-Host ""
        Write-Host "============================================================" -ForegroundColor Green
        Write-OK "Service installed & RUNNING."
        Write-Host "============================================================" -ForegroundColor Green
        Write-Host "  Status:  Get-Service ${SERVICE_NAME}"
        Write-Host "  Stop:    Stop-Service ${SERVICE_NAME}"
        Write-Host "  Start:   Start-Service ${SERVICE_NAME}"
        Write-Host "  Logs:    $InstallDir\\daemon.log"
        Write-Host ""
        exit 0
    }

    # -- Step 7b: foreground run + post-launch verify --------------------------
    Write-Step "7/7 Starting daemon (FOREGROUND mode - debug/testing)..." 'Yellow'
    Write-Host "  Mode ini cuma untuk debug. Tutup window = daemon mati. PC restart = daemon ga auto-start." -ForegroundColor Yellow
    Write-Host "  Untuk production 24/7: Ctrl+C window ini, terus run installer LAGI sebagai Administrator (default = Service mode auto-start)." -ForegroundColor DarkGray
    Write-Host ""
    Write-Host "============================================================" -ForegroundColor Green
    Write-Host "  yeehee daemon - SIAP" -ForegroundColor Green
    Write-Host "  Cek status di HP: yeehee.vercel.app/more/settings" -ForegroundColor DarkGray
    Write-Host "  Stop: Ctrl+C" -ForegroundColor DarkGray
    Write-Host "============================================================" -ForegroundColor Green
    Write-Host ""

    # Start daemon. Will block sampai Ctrl+C atau crash.
    & $Py -m daemon.main
    $exitCode = $LASTEXITCODE

    # Daemon ended
    Write-Host ""
    if ($exitCode -ne 0 -and $exitCode -ne $null) {
        Write-Host "[yeehee] [WARN] Daemon exited code $exitCode (bukan Ctrl+C clean shutdown)" -ForegroundColor Yellow
        Write-Host "  Restart: python -m daemon.main (di folder $InstallDir)" -ForegroundColor DarkGray
        Write-Host "  Atau install Service biar auto-restart kalau crash. Run installer ULANG sebagai Administrator (default = Service mode)." -ForegroundColor DarkGray
    } else {
        Write-Host "[yeehee] Daemon stopped clean (Ctrl+C). Sampai jumpa." -ForegroundColor Cyan
    }
}
catch {
    Write-Host ""
    Write-Host "============================================================" -ForegroundColor Red
    Write-Host "[yeehee] [ERROR] Install gagal:" -ForegroundColor Red
    Write-Host "  $($_.Exception.Message)"      -ForegroundColor Red
    Write-Host "============================================================" -ForegroundColor Red
    Write-Host ""
    Write-Host "Detail di atas log warna abu-abu."
    Write-Host "Tekan Enter untuk tutup window..."
    [void](Read-Host)
    exit 1
}
`

export async function GET() {
  // UTF-8 BOM (﻿) so PowerShell 5.1 (default Windows-1252 codepage) auto-detects encoding
  const BOM = '﻿'
  return new NextResponse(BOM + SCRIPT, {
    status: 200,
    headers: {
      'Content-Type':                'text/plain; charset=utf-8',
      'Cache-Control':               'no-store, no-cache, must-revalidate',
      'Content-Disposition':         'inline; filename="yeehee-setup.ps1"',
      'Access-Control-Allow-Origin': '*',
    },
  })
}
